version: '2'
services:
    coding_in_jhipster-app:
        image: coding_in_jhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://coding_in_jhipster-mysql:3306/coding_in_jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    coding_in_jhipster-mysql:
        extends:
            file: mysql.yml
            service: coding_in_jhipster-mysql
